### PR TITLE
logos update

### PR DESCRIPTION
**Pull request by damianodamiani**
I cleaned up the fonts, streamlined our logos (biggest change: added erc to the readchina logo so it always fits) and removed some unused files

### CODE REVIEW

**Review by duncdrum — CHANGES_REQUESTED** [review]
i was using the svgs, they are quite useful for the web, as they scale automatically, can you please leave them in, or better yet create updated ones?

the ERC logo [according to their site](https://erc.europa.eu/managing-your-project/communicating-your-research) and the EU flag should "always we displayed together" , can you also import a properly scaled flag logo so we can use them together?

**Comment by damianodamiani** [comment]
hey, svgs addedd, sorry didn't know they're being used :)

About the flag, I'm not very happy about that idea - I also checked a bunch of erc funded projects and none is using the EU flag in their logos, seems like an overkill to me... 

@LenaHenningsen What's your opinion on this? I am happy to redesign the logos as instructed.

**Comment by duncdrum** [comment]
I m not suggesting to add the EU flag to our logo, but to keep a separate logo (just the flag) so we can make it point to the ERC, while our logo (which includes both ERC and RC) points to us. This would follow their request to only display their logo next to the flag. 

We can't just have one giant logo with all agencies in one file, for online contents, we need pop-ups and links to go to whoever it is the logo represents. 

I have neither strong feelings pro or against the flag, but their guidelines are quite clear and they make the point repeatedly.

**Comment by LenaHenningsen** [comment]
Thanks for asking - if the ERC wants the flag, then let's add it. As long as it is not the ugly German flag, or any other national flag (or the Bavarian one), I have no objections to anything.
By the way: do we want to add the Young Academy and Baden Württemberg, too? We have the logo for the latter on the old homepage for Lesewelten: http://www.sinologie.uni-freiburg.de/forschung/projecthenningsen

**Comment by duncdrum** [comment]
@LenaHenningsen i wouldn’t . I have added the logos to the redact page but here is for the erc project, which means all of our presentations etc, but not the past funding for Lesewelten. Uni Freiburg we could do

**Comment by damianodamiani** [comment]
revised logos as decided, not they're in all shapes and sizes, with flag and without, in black and in white, transparent and in colors. Take and use it as pleased, the PNGs should be used at all times unless SVG more desires, in case of uncertainty consult the illustrator file.

**Comment by damianodamiani** [comment]
what about this PR @duncdrum ? any other changes or good to go?

**Review by duncdrum — APPROVED** [review]

**Pull request merged**
